
import Database.Star_server;
import snake.Splash;
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Sidiq
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        btn_log_Off.setVisible(false);
        btn_formbarang.setVisible(false);
        btn_formPeminjam.setVisible(false);
        btn_formUser.setVisible(false);
        btn_transaksi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_formUser = new usu.widget.ButtonGlass();
        btn_transaksi = new usu.widget.ButtonGlass();
        btn_formPeminjam = new usu.widget.ButtonGlass();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btn_snake = new usu.widget.ButtonGlass();
        btn_login = new usu.widget.ButtonGlass();
        btn_formbarang = new usu.widget.ButtonGlass();
        btn_log_Off = new usu.widget.ButtonGlass();
        btn_closee = new usu.widget.ButtonGlass();
        btn_closee1 = new usu.widget.ButtonGlass();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Server");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_formUser.setForeground(new java.awt.Color(255, 255, 255));
        btn_formUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_iconn.png"))); // NOI18N
        btn_formUser.setText("Add User");
        btn_formUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_formUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formUserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_formUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 210, 80));

        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transactionBarang.png"))); // NOI18N
        btn_transaksi.setText("Kembali Barang");
        btn_transaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 80));

        btn_formPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        btn_formPeminjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/borrow-barang.png"))); // NOI18N
        btn_formPeminjam.setText("Pinjam Barang");
        btn_formPeminjam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_formPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formPeminjamActionPerformed(evt);
            }
        });
        getContentPane().add(btn_formPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 80));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1150, 790));

        btn_snake.setForeground(new java.awt.Color(255, 255, 255));
        btn_snake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/snake-removebg-preview.png"))); // NOI18N
        btn_snake.setText("SNAKE GAME");
        btn_snake.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_snake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_snakeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_snake, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 210, 80));

        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginoke.png"))); // NOI18N
        btn_login.setText("LOGIN");
        btn_login.setActionCommand("login");
        btn_login.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 80));

        btn_formbarang.setForeground(new java.awt.Color(255, 255, 255));
        btn_formbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-file_barang.png"))); // NOI18N
        btn_formbarang.setText("Add Barang");
        btn_formbarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_formbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formbarangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_formbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, 80));

        btn_log_Off.setForeground(new java.awt.Color(255, 255, 255));
        btn_log_Off.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log_off copy.png"))); // NOI18N
        btn_log_Off.setText("Log Off");
        btn_log_Off.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_log_Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_OffActionPerformed(evt);
            }
        });
        getContentPane().add(btn_log_Off, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 80));

        btn_closee.setForeground(new java.awt.Color(255, 255, 255));
        btn_closee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        btn_closee.setText("Exit");
        btn_closee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_closee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_closee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 210, 80));

        btn_closee1.setForeground(new java.awt.Color(255, 255, 255));
        btn_closee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/about.png"))); // NOI18N
        btn_closee1.setText("Kelompok");
        btn_closee1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_closee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closee1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_closee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 210, 80));

        jLabel1.setBackground(new java.awt.Color(153, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homeoke.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_formUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formUserActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_user fm = new Form_user();
        fm.setVisible(true);
        jDesktopPane1.add(fm);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_formUserActionPerformed

    private void btn_formPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formPeminjamActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_Peminjam fm = new Form_Peminjam();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_btn_formPeminjamActionPerformed

    private void btn_snakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_snakeActionPerformed
        Splash fm = new Splash();
        fm.setVisible(true);
         // TODO add your handling code here:
    }//GEN-LAST:event_btn_snakeActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        //jDesktopPane1.removeAll();
        //jDesktopPane1.repaint();
        
        Login_server fm = new Login_server();
        fm.setVisible(true);
        //jDesktopPane1.add(fm);


    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_Pengembalian fm = new Form_Pengembalian();
        fm.setVisible(true);
        jDesktopPane1.add(fm);// TODO add your handling code here:
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_log_OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_OffActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        btn_login.setVisible(true);
        btn_log_Off.setVisible(false);
        btn_formbarang.setVisible(false);
        btn_snake.setVisible(false);
        btn_formPeminjam.setVisible(false);
        btn_formUser.setVisible(false);
        btn_transaksi.setVisible(false);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_log_OffActionPerformed

    private void btn_closeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_closeeActionPerformed

    private void btn_closee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closee1ActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        About_ a = new About_();
        a.setVisible(true);
        jDesktopPane1.add(a);
    }//GEN-LAST:event_btn_closee1ActionPerformed

    private void btn_formbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formbarangActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Form_Barang fm = new Form_Barang();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_btn_formbarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    public void admin() {
        btn_snake.setVisible(true);
        btn_formbarang.setVisible(true);
        btn_formPeminjam.setVisible(true);
        btn_formUser.setVisible(true);
        btn_log_Off.setVisible(true);
        btn_login.setVisible(false);
        btn_transaksi.setVisible(true);
        

    }

    public void user() {
        btn_snake.setVisible(true);
        btn_formPeminjam.setVisible(true);
        btn_formUser.setVisible(false);
        btn_log_Off.setVisible(true);
        btn_login.setVisible(false);
        btn_transaksi.setVisible(true);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static usu.widget.ButtonGlass btn_closee;
    public static usu.widget.ButtonGlass btn_closee1;
    public static usu.widget.ButtonGlass btn_formPeminjam;
    public static usu.widget.ButtonGlass btn_formUser;
    public static usu.widget.ButtonGlass btn_formbarang;
    public static usu.widget.ButtonGlass btn_log_Off;
    public static usu.widget.ButtonGlass btn_login;
    public static usu.widget.ButtonGlass btn_snake;
    public static usu.widget.ButtonGlass btn_transaksi;
    public static javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
